defaults: &defaults
  autocreate_indexes: false
  allow_dynamic_fields: true
  include_root_in_json: false
  parameterize_keys: true
  persist_in_safe_mode: false
  raise_not_found_error: true
  reconnect_time: 3

micro_production:
  <<: *defaults
  host: stage03.miningbased.com
  slaves:
    - host: drone01.miningbased.com
    - host: drone02.miningbased.com
  database: micro_production

micro:
  <<: *defaults
  host: stage03.miningbased.com
  slaves:
    - host: drone01.miningbased.com
    - host: drone02.miningbased.com
  database: micro_development

test:
  <<: *micro
  database: micro_test

micro_mthorley:
  <<: *defaults
  host: stage03.miningbased.com
  slaves:
    - host: drone01.miningbased.com
    - host: drone02.miningbased.com
  database: micro_mthorley
